"""Initial schema snapshot

Revision ID: 1be49a789bed
Revises: 
Create Date: 2025-10-05 14:25:19.406838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be49a789bed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'device_uid',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('device', 'allowed_minutes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_order_payment_id', table_name='order')
    op.drop_index('idx_order_payment_status', table_name='order')
    op.drop_constraint('order_payment_id_key', 'order', type_='unique')
    op.create_index(op.f('ix_order_payment_id'), 'order', ['payment_id'], unique=True)
    op.drop_index('idx_user_parent_id', table_name='user')
    op.create_index(op.f('ix_user_parent_id'), 'user', ['parent_id'], unique=False)
    op.drop_constraint('user_parent_fk', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_parent_fk', 'user', 'user', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_user_parent_id'), table_name='user')
    op.create_index('idx_user_parent_id', 'user', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_order_payment_id'), table_name='order')
    op.create_unique_constraint('order_payment_id_key', 'order', ['payment_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_order_payment_status', 'order', ['payment_status'], unique=False)
    op.create_index('idx_order_payment_id', 'order', ['payment_id'], unique=False)
    op.alter_column('device', 'allowed_minutes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('device', 'device_uid',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
